export const RESOURCES_TO_RESET = [
  // Ordre important : d'abord les dépendants
  { name: 'Tickets',          endpoint: '/Assistance/Ticket' },
  { name: 'Changes',          endpoint: '/Assistance/Change' },
  { name: 'Problems',         endpoint: '/Assistance/Problem' },
  { name: 'Computers',        endpoint: '/Assets/Computer' },
  { name: 'Monitors',         endpoint: '/Assets/Monitor' },
  { name: 'Phones',           endpoint: '/Assets/Phone' },
  // { name: 'Racks',         endpoint: '/Assets/Rack' },
  // { name: 'PDUs',         endpoint: '/Assets/PDU' },
  // { name: 'Enclosures',   endpoint: '/Assets/Enclosure' },
  // { name: 'Appliances',   endpoint: '/Assets/Appliance' },
  // { name: 'NetworkEquipment', endpoint: '/Assets/NetworkEquipment' },
  // { name: 'PassiveDCEquipments', endpoint: '/Assets/PassiveDCEquipment' },
  // { name: 'Sockets', endpoint: '/Assets/Socket' },
  // { name: 'Printers',         endpoint: '/Assets/Printer' },
  // { name: 'Peripherals',      endpoint: '/Assets/Peripheral' },
  // { name: 'Software',         endpoint: '/Assets/Software' },
  // { name: 'SoftwareLicense',  endpoint: '/Assets/SoftwareLicense' },
  // { name: 'Certificates',  endpoint: '/Assets/Certificate' },
  { name: 'Contracts',        endpoint: '/Management/Contract' },
  { name: 'Documents',        endpoint: '/Management/Document' },
  { name: 'Budgets',          endpoint: '/Management/Budget' },
  { name: 'Suppliers',        endpoint: '/Management/Supplier' },
  { name: 'Contacts',         endpoint: '/Management/Contact' },
  { name: 'Projects',         endpoint: '/Project' },
  { name: 'Locations',         endpoint: '/DropDowns/Location' },
  { name: 'Manufacturer',         endpoint: '/DropDowns/Manufacturer' },
  { name: 'ComputerModels',         endpoint: '/DropDowns/ComputerModel' },
  { name: 'MonitorModels',         endpoint: '/DropDowns/MonitorModel' },
  // { name: 'NetworkEquipmentModels',         endpoint: '/DropDowns/NetworkEquipmentModel' },
  // { name: 'EnclosureModels',         endpoint: '/DropDowns/EnclosureModel' },
  // { name: 'EnclosureModels',         endpoint: '/DropDowns/PeripheralModel' },
  // { name: 'RackModels',         endpoint: '/DropDowns/VirtualMachineModel' },
  { name: 'PhoneModels',         endpoint: '/DropDowns/PhoneModel' },
  { name: 'ComputerType',         endpoint: '/Dropdowns/ComputerType' },
  { name: 'MonitorType',         endpoint: '/Dropdowns/MonitorType' },
  { name: 'States',         endpoint: '/DropDowns/State' },
  { name: 'Users',            endpoint: '/Administration/User',
    protectedIds: [1,2,3,4,5,6] },
    { name:'Groups', endpoint:'/Administration/Group',protectedIds:[0]},
    {name:'Entities', endpoint: '/Administration/Entity', protectedIds:[0]},
    {name:'Profiles', endpoint:'/Administration/Profile', protectedIds:[1,2,3,4,5,6,7,8]}
  // { name: 'PrinterType',         endpoint: '/Dropdowns/PrinterType' },
  // { name: 'NetworkEquipmentType',         endpoint: '/Dropdowns/NetworkEquipmentType' },
  // { name: 'PeripheralType',         endpoint: '/Dropdowns/PeripheralType' },
  // { name: 'PhoneType',         endpoint: '/Dropdowns/PhoneType' },
  // { name: 'HardDriveType',         endpoint: '/Dropdowns/HardDriveType' },
  // { name: 'CableType',         endpoint: '/Dropdowns/CableType' },
  // { name: 'CartridgeItemType',         endpoint: '/Dropdowns/CartridgeItemType' },
  // { name: 'ConsumableItemType',         endpoint: '/Dropdowns/ConsumableItemType' },
  // { name: 'VirtualMachineType',         endpoint: '/Dropdowns/VirtualMachineType' },
  // Users en dernier, avec exceptions
  
];  